In [47]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#한글형태소 추출 라이브러리 설치
!pip install KoNLPy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting KoNLPy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     |████████████████████████████████| 19.4 MB 4.3 MB/s
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from KoNLPy) (1.21.6)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from KoNLPy) (4.2.6)
Collecting JPype1>=0.7.0
  Downloading JPype1-1.4.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (453 kB)
     |████████████████████████████████| 453 kB 53.9 MB/s
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->KoNLPy) (4.1.1)
Installing collected packages: JPype1, KoNLPy
Successfully installed JPype1-1.4.0 KoNLPy-0.6.0

In [48]:
#모델 생성
from konlpy.tag import Komoran
komoran = Komoran()

In [67]:
import pandas as pd
import numpy as np

#영화 리뷰데이터 가져오기
reviews = pd.read_csv('/content/drive/MyDrive/movie_reviews_ver3.csv')
reviews

,Unnamed: 0,Unnamed: 0.1,titles,rates,reviews,isit_domestic
0,0,0,미니언즈2,10,미니언즈가 귀여운데 알아듣지 못하는 말을 해서 아쉽다. 어린이 조카가 무지 좋아한...,False
1,1,1,아이언 크로스: 노르망디 상륙작전,10,전투 액션이 좋네요...스케일이 엄청납니다,False
2,2,2,외계+인 1부,10,호불호가 있다고 했지만 재밌게 봤어요 2부도 기대 됩니다,True
3,3,3,메기,1,편하고 안전하게만 살아온 사람들만 공감할 수 있는 피해 망상의 영화…,True
4,4,4,헤어질 결심,10,"많은 여운을 남긴 영화, 탕웨이 예뻐요!!",True
...,...,...,...,...,...,...
9985,9985,9985,씨 비스트,10,뻔한스토리 전혀 없음 좋은 영화 아끼는 사람들과 함께 보세요,True
9986,9986,9986,헤어질 결심,10,기대 안 하고 봤는데 정말 재미있었습니다.,True
9987,9987,9987,그레이 맨,10,인생 액션영화 리스트에 저장했습니다.2시간 정말지루하지 않고 몰입감 있는 전개는 ...,False
9988,9988,9988,외계+인 1부,8,신선하고 재밌었어요. 평이 안 좋아서 기대를 안하고 가서 그랬는지 의외로 괜찮더라구...,True
9989,9989,9989,아무도 모른다,10,엄마가 첫째에게 돈을 남기고 갔을때 아들이 놀라지 않고 돈이 얼마인지 세는 장면이...,True

In [ ]:
#빈칸 지우기
review = []
for i in range(0, reviews.shape[0]):
  string = reviews.iloc[i,4]
  string = str(string) #형변환(float to string)
  string_2 = string.replace("  ","")
  print(i)
  print(string_2 + "end") #끝나는 것 재확인
  review.append(string_2)

In [84]:
lists = []

#토큰화 진행
for i in range(0, reviews.shape[0]):
  try:
    mini_1 = komoran.pos(review[i])
    mini_2 = []
    for k in mini_1:
      if k[1] in ('NNG', 'NNP', 'MM', 'MAG', 'IC', 'NF', 'NV'):
        mini_2.append(k[0])
      elif k[1] in ('VV', 'VA'):
        mini_2.append(k[0]+"다")
  except:
    mini_2.append("")
  lists.append(mini_2)

#리스트에 저장 후 영화리뷰데이터에 별도 열로 추가
reviews['komoran'] = lists

In [85]:
#결과
reviews

,Unnamed: 0,Unnamed: 0.1,titles,rates,reviews,isit_domestic,komoran
0,0,0,미니언즈2,10,미니언즈가 귀여운데 알아듣지 못하는 말을 해서 아쉽다. 어린이 조카가 무지 좋아한...,False,"[미니언즈, 귀엽다, 알아듣다, 말, 하다, 아쉽다, 어린이, 조카, 무지, 좋아하다]"
1,1,1,아이언 크로스: 노르망디 상륙작전,10,전투 액션이 좋네요...스케일이 엄청납니다,False,"[전투, 액션, 좋다, 스케일, 엄청나다]"
2,2,2,외계+인 1부,10,호불호가 있다고 했지만 재밌게 봤어요 2부도 기대 됩니다,True,"[불, 호가, 있다, 하다, 재밌다, 보다, 부도, 기대, 되다]"
3,3,3,메기,1,편하고 안전하게만 살아온 사람들만 공감할 수 있는 피해 망상의 영화…,True,"[편하다, 안전, 살아오다, 사람, 공감, 있다, 피해, 망상, 영화]"
4,4,4,헤어질 결심,10,"많은 여운을 남긴 영화, 탕웨이 예뻐요!!",True,"[많다, 여운, 남기다, 영화, 탕웨이, 예뻐, 요, !!]"
...,...,...,...,...,...,...,...
9985,9985,9985,씨 비스트,10,뻔한스토리 전혀 없음 좋은 영화 아끼는 사람들과 함께 보세요,True,"[뻔하다, 스토리, 전혀, 없다, 좋다, 영화, 아끼다, 사람, 함께, 보다]"
9986,9986,9986,헤어질 결심,10,기대 안 하고 봤는데 정말 재미있었습니다.,True,"[기대, 안, 하다, 보다, 정말, 재미있다]"
9987,9987,9987,그레이 맨,10,인생 액션영화 리스트에 저장했습니다.2시간 정말지루하지 않고 몰입감 있는 전개는 ...,False,"[인생, 액션, 영화, 리스트, 저장, 시간, 정말, 지루, 하지, 몰입, 감, 있..."
9988,9988,9988,외계+인 1부,8,신선하고 재밌었어요. 평이 안 좋아서 기대를 안하고 가서 그랬는지 의외로 괜찮더라구...,True,"[재밌다, 안, 좋아서, 기대, 안, 가다, 그렇다, 의외로, 괜찮다, 후반부, 몰..."
9989,9989,9989,아무도 모른다,10,엄마가 첫째에게 돈을 남기고 갔을때 아들이 놀라지 않고 돈이 얼마인지 세는 장면이...,True,"[엄마, 돈, 남기다, 가다, 때, 아들, 놀라다, 돈, 얼마, 장면, 가장, 마음..."

In [86]:
reviews.to_csv('movie_reviews_with_komoran.csv')